import React from 'react';
import { useParams, Link } from 'react-router-dom';
import './ChapterList.css';

const ChapterList: React.FC = () => {
  const { grade, subject } = useParams<{ grade: string; subject: string }>();

  const ncertChapters: { [key: string]: { [key: string]: { name: string; description: string; }[] } } = {
    '6': {
      'Mathematics': [
        { name: 'Knowing Our Numbers', description: 'Overview of number systems.' },
        { name: 'Whole Numbers', description: 'Properties and operations of whole numbers.' },
        { name: 'Playing with Numbers', description: 'Divisibility rules, factors, and multiples.' },
        { name: 'Basic Geometrical Ideas', description: 'Introduction to basic geometric shapes.' },
        { name: 'Understanding Elementary Shapes', description: 'Types of angles, triangles, and quadrilaterals.' },
        { name: 'Integers', description: 'Positive and negative numbers.' },
        { name: 'Fractions', description: 'Understanding parts of a whole.' },
        { name: 'Decimals', description: 'Decimal representation of numbers.' },
        { name: 'Data Handling', description: 'Collecting, organizing, and interpreting data.' },
        { name: 'Mensuration', description: 'Perimeter and area of plane figures.' },
        { name: 'Algebra', description: 'Introduction to variables and equations.' },
        { name: 'Ratio and Proportion', description: 'Comparing quantities.' },
        { name: 'Symmetry', description: 'Understanding symmetrical shapes.' },
        { name: 'Practical Geometry', description: 'Construction of basic geometric figures.' },
      ],
      'Science': [
        { name: 'Food: Where Does It Come From?', description: 'Sources of food and its components.' },
        { name: 'Components of Food', description: 'Nutrients and their importance.' },
        { name: 'Fibre to Fabric', description: 'Journey from fibre to cloth.' },
        { name: 'Sorting Materials into Groups', description: 'Properties of materials.' },
        { name: 'Separation of Substances', description: 'Methods of separating mixtures.' },
        { name: 'Changes Around Us', description: 'Reversible and irreversible changes.' },
        { name: 'Getting to Know Plants', description: 'Parts of plants and their functions.' },
        { name: 'Body Movements', description: 'Skeletal system and movement in animals.' },
        { name: 'The Living Organisms and Their Surroundings', description: 'Habitats and adaptations.' },
        { name: 'Motion and Measurement of Distances', description: 'Types of motion and measurement units.' },
        { name: 'Light, Shadows and Reflections', description: 'Formation of shadows and reflection of light.' },
        { name: 'Electricity and Circuits', description: 'Electric current and simple circuits.' },
        { name: 'Fun with Magnets', description: 'Properties of magnets and their uses.' },
        { name: 'Water', description: 'Importance of water and its conservation.' },
        { name: 'Air Around Us', description: 'Composition and properties of air.' },
        { name: 'Garbage In, Garbage Out', description: 'Waste management and disposal.' },
      ],
      'Social Science': [
        { name: 'The Earth in the Solar System', description: 'Our planet and its place in the cosmos.' },
        { name: 'Globe: Latitudes and Longitudes', description: 'Understanding Earth\'s grid system.' },
        { name: 'Motions of the Earth', description: 'Rotation, revolution, and seasons.' },
        { name: 'Maps', description: 'Types of maps and their components.' },
        { name: 'Major Domains of the Earth', description: 'Lithosphere, hydrosphere, atmosphere, and biosphere.' },
        { name: 'Our Country – India', description: 'Geographical features and diversity of India.' },
        { name: 'India: Climate, Vegetation and Wildlife', description: 'Climate, natural vegetation, and wildlife of India.' },
        { name: 'What, Where, How and When?', description: 'Understanding ancient history and its sources.' },
        { name: 'From Hunting – Gathering to Growing Food', description: 'The transition to settled life.' },
        { name: 'In the Earliest Cities', description: 'The Harappan Civilization and its features.' },
        { name: 'What Books and Burials Tell Us', description: 'Insights from ancient texts and burial sites.' },
        { name: 'Kingdoms, Kings and an Early Republic', description: 'Rise of early states and social structures.' },
        { name: 'New Questions and Ideas', description: 'Emergence of Buddhism and Jainism.' },
        { name: 'From a Kingdom to an Empire', description: 'The Mauryan Empire and Ashoka\'s rule.' },
        { name: 'Villages, Towns and Trade', description: 'Rural and urban life, and economic activities.' },
        { name: 'New Empires and Kingdoms', description: 'The Gupta Empire and other powerful dynasties.' },
        { name: 'Buildings, Paintings and Books', description: 'Ancient Indian art, architecture, and literature.' },
        { name: 'Understanding Diversity', description: 'Recognizing and respecting individual differences.' },
        { name: 'Diversity and Discrimination', description: 'Causes and effects of prejudice and discrimination.' },
        { name: 'What is Government', description: 'Role and types of government.' },
        { name: 'Key Elements of a Democratic Government', description: 'Participation, conflict resolution, equality, and justice.' },
        { name: 'Panchayati Raj', description: 'Local self-government in rural areas.' },
        { name: 'Rural Administration', description: 'Maintaining law and order and land records in villages.' },
        { name: 'Urban Administration', description: 'Managing cities and providing public services.' },
        { name: 'Rural Livelihoods', description: 'Farming and non-farming activities in villages.' },
        { name: 'Urban Livelihoods', description: 'Diverse occupations in cities.' },
      ],
      'English': [
        { name: 'Who Did Patricks Homework', description: 'Honeysuckle Chapter 1' },
        { name: 'How the Dog Found Himself a New Master', description: 'Honeysuckle Chapter 2' },
        { name: 'Taros Reward', description: 'Honeysuckle Chapter 3' },
        { name: 'An Indian American Woman in Space Kalpana Chawla', description: 'Honeysuckle Chapter 4' },
        { name: 'A Different Kind of School', description: 'Honeysuckle Chapter 5' },
        { name: 'Who I Am', description: 'Honeysuckle Chapter 6' },
        { name: 'Fair Play', description: 'Honeysuckle Chapter 7' },
        { name: 'A Game of Chance', description: 'Honeysuckle Chapter 8' },
        { name: 'Desert Animals', description: 'Honeysuckle Chapter 9' },
        { name: 'The Banyan Tree', description: 'Honeysuckle Chapter 10' },
        { name: 'A House A Home', description: 'Honeysuckle Chapter 1' },
        { name: 'The Kite', description: 'Honeysuckle - Poetry' },
        { name: 'The Quarrel', description: 'Honeysuckle - Poetry' },
        { name: 'Beauty', description: 'Honeysuckle - Poetry' },
        { name: 'Where Do All the Teachers Go', description: 'Honeysuckle - Poetry' },
        { name: 'The Wonderful Words', description: 'Honeysuckle - Poetry' },
        { name: 'Vocation', description: 'Honeysuckle - Poetry' },
        { name: 'What if', description: 'Honeysuckle - Poetry' },
        { name: 'A Tale of Two Birds', description: 'A Pact with the Sun Chapter 1' },
        { name: 'The Friendly Mongoose', description: 'A Pact with the Sun Chapter 2' },
        { name: 'The Shepherds Treasure', description: 'A Pact with the Sun Chapter 3' },
        { name: 'The Old Clock Shop', description: 'A Pact with the Sun Chapter 4' },
        { name: 'Tansen', description: 'A Pact with the Sun Chapter 5' },
        { name: 'The Monkey and the Crocodile', description: 'A Pact with the Sun Chapter 6' },
        { name: 'The Wonder Called Sleep', description: 'A Pact with the Sun Chapter 7' },
        { name: 'A Pact with the Sun', description: 'A Pact with the Sun Chapter 8' },
        { name: 'What Happened To the Reptiles', description: 'A Pact with the Sun Chapter 9' },
        { name: 'A Strange Wrestling Match', description: 'A Pact with the Sun Chapter 10' },
      ],
      'Hindi': [
        { name: 'Vah Chidiya Jo', description: 'वह चिड़िया जो (Vasant)' },
        { name: 'Bachpan', description: 'बचपन (Vasant)' },
        { name: 'Naadaan Dost', description: 'नादान दोस्त (Vasant)' },
        { name: 'Chand se Thodi-si Gappein', description: 'चाँद से थोड़ी-सी गप्पें (Vasant)' },
        { name: 'Aksharon Ka Mahatv', description: 'अक्षरों का महत्व (Vasant)' },
        { name: 'Paar Nazar Ke', description: 'पार नज़र के (Vasant)' },
        { name: 'Saathi Haath Badhaana', description: 'साथी हाथ बढ़ाना (Vasant)' },
        { name: 'Aise-Aise', description: 'ऐसे-ऐसे (Vasant)' },
        { name: 'Tikat Albam', description: 'टिकट अलबम (Vasant)' },
        { name: 'Jhansi Ki Rani', description: 'झाँसी की रानी (Vasant)' },
        { name: 'Jo Dekhkar Bhi Nahin Dekhte', description: 'जो देखकर भी नहीं देखते (Vasant)' },
        { name: 'Sansar Pustak Hai', description: 'संसार पुस्तक है (Vasant)' },
        { name: 'Main Sabse Chhoti Hoon', description: 'मैं सबसे छोटी होऊँ (Vasant)' },
        { name: 'Lokageet', description: 'लोकगीत (Vasant)' },
        { name: 'Naukar', description: 'नौकर (Vasant)' },
        { name: 'Van Ke Maarg Mein', description: 'वन के मार्ग में (Vasant)' },
        { name: 'Saans-Saans Mein Baans', description: 'साँस-साँस में बाँस (Vasant)' },
      ],
    },
    '7': {
      'Mathematics': [
        { name: 'Integers', description: 'Positive and negative numbers.' },
        { name: 'Fractions and Decimals', description: 'Operations with fractions and decimals.' },
        { name: 'Data Handling', description: 'Collecting, organizing, and interpreting data.' },
        { name: 'Simple Equations', description: 'Solving linear equations.' },
        { name: 'Lines and Angles', description: 'Properties of lines and angles.' },
        { name: 'The Triangle and Its Properties', description: 'Types of triangles and their properties.' },
        { name: 'Congruence of Triangles', description: 'Conditions for congruence of triangles.' },
        { name: 'Comparing Quantities', description: 'Ratio, proportion, and percentage.' },
        { name: 'Rational Numbers', description: 'Understanding rational numbers.' },
        { name: 'Practical Geometry', description: 'Construction of triangles and other figures.' },
        { name: 'Perimeter and Area', description: 'Calculating perimeter and area of plane figures.' },
        { name: 'Algebraic Expressions', description: 'Operations with algebraic expressions.' },
        { name: 'Exponents and Powers', description: 'Understanding exponents and powers.' },
        { name: 'Symmetry', description: 'Rotational and reflectional symmetry.' },
        { name: 'Visualising Solid Shapes', description: 'Understanding 3D shapes.' },
      ],
      'Science': [
        { name: 'Nutrition in Plants', description: 'Modes of nutrition in plants.' },
        { name: 'Nutrition in Animals', description: 'Modes of nutrition in animals.' },
        { name: 'Fibre to Fabric', description: 'Processing of animal fibres.' },
        { name: 'Heat', description: 'Transfer of heat and its effects.' },
        { name: 'Acids, Bases and Salts', description: 'Properties and uses of acids, bases, and salts.' },
        { name: 'Physical and Chemical Changes', description: 'Distinguishing between physical and chemical changes.' },
        { name: 'Weather, Climate and Adaptations of Animals to Climate', description: 'Impact of weather and climate on animals.' },
        { name: 'Winds, Storms and Cyclones', description: 'Formation and effects of winds, storms, and cyclones.' },
        { name: 'Soil', description: 'Types of soil and its properties.' },
        { name: 'Respiration in Organisms', description: 'Process of respiration in living beings.' },
        { name: 'Transportation in Animals and Plants', description: 'Circulatory and transport systems.' },
        { name: 'Reproduction in Plants', description: 'Modes of reproduction in plants.' },
        { name: 'Motion and Time', description: 'Measurement of speed and time.' },
        { name: 'Electric Current and Its Effects', description: 'Heating, magnetic, and chemical effects of electric current.' },
        { name: 'Light', description: 'Reflection and refraction of light.' },
        { name: 'Forests: Our Lifeline', description: 'Importance of forests and their conservation.' },
        { name: 'Wastewater Story', description: 'Treatment and disposal of wastewater.' },
      ],
      'Social Science': [
        { name: 'Tracing Changes Through a Thousand Years', description: 'Evolution of societies over time.' },
        { name: 'New Kings and Kingdoms', description: 'Emergence of new dynasties and empires.' },
        { name: 'The Delhi Sultans', description: 'Rule of the Delhi Sultanate.' },
        { name: 'The Mughal Empire', description: 'Rise and fall of the Mughal Empire.' },
        { name: 'Rulers and Buildings', description: 'Architectural achievements of rulers.' },
        { name: 'Towns, Traders, and Craftspersons', description: 'Urban centers and economic activities.' },
        { name: 'Tribes, Nomads and Settled Communities', description: 'Different forms of social organization.' },
        { name: 'Devotional Paths to the Divine', description: 'Bhakti and Sufi movements.' },
        { name: 'The Making of Regional Cultures', description: 'Development of distinct regional identities.' },
        { name: 'Eighteenth-Century Political Formations', description: 'Political changes in the 18th century.' },
        { name: 'Environment', description: 'Components of the natural environment.' },
        { name: 'Inside Our Earth', description: 'Structure and composition of the Earth.' },
        { name: 'Our Changing Earth', description: 'Forces shaping the Earth\'s surface.' },
        { name: 'Air', description: 'Composition and structure of the atmosphere.' },
        { name: 'Water', description: 'Water cycle and water bodies.' },
        { name: 'Natural Vegetation and Wildlife', description: 'Types of vegetation and animal life.' },
        { name: 'Human Environment – Settlement, Transport and Communication', description: 'Human interaction with the environment.' },
        { name: 'Human Environment Interactions – The Tropical and the Subtropical Region', description: 'Life in different climatic zones.' },
        { name: 'Life in the Temperate Grasslands', description: 'Adaptations to grassland environments.' },
        { name: 'Life in the Deserts', description: 'Life in arid regions.' },
        { name: 'On Equality', description: 'Understanding equality and discrimination.' },
        { name: 'Role of the Government in Health', description: 'Government\'s role in public health.' },
        { name: 'How the State Government Works', description: 'Functions of state government.' },
        { name: 'Growing Up as Boys and Girls', description: 'Gender roles and stereotypes.' },
        { name: 'Women Change the World', description: 'Contributions of women to society.' },
        { name: 'Understanding Media', description: 'Role of media in democracy.' },
        { name: 'Markets Around Us', description: 'Types of markets and their functions.' },
        { name: 'A Shirt in the Market', description: 'Journey of a shirt from production to sale.' },
        { name: 'Struggles for Equality', description: 'Movements for social justice.' },
      ],
      'English': [
        { name: 'Three Questions', description: 'Honeycomb - Prose' },
        { name: 'A Gift of Chappals', description: 'Honeycomb - Prose' },
        { name: 'Gopal and the Hilsa Fish', description: 'Honeycomb - Prose' },
        { name: 'The Ashes That Made Trees Bloom', description: 'Honeycomb - Prose' },
        { name: 'Quality', description: 'Honeycomb - Prose' },
        { name: 'Expert Detectives', description: 'Honeycomb - Prose' },
        { name: 'The Invention of Vita-Wonk', description: 'Honeycomb - Prose' },
        { name: 'A Homage to our Brave Soldiers', description: 'Honeycomb - Prose' },
        { name: 'The Squirrel', description: 'Honeycomb - Poetry' },
        { name: 'The Rebel', description: 'Honeycomb - Poetry' },
        { name: 'The Shed', description: 'Honeycomb - Poetry' },
        { name: 'Chivvy', description: 'Honeycomb - Poetry' },
        { name: 'Trees', description: 'Honeycomb - Poetry' },
        { name: 'Mystery of the Talking Fan', description: 'Honeycomb - Poetry' },
        { name: 'Dad and the Cat and the Tree', description: 'Honeycomb - Poetry' },
        { name: 'Garden Snake', description: 'Honeycomb - Poetry' },
        { name: 'The Tiny Teacher', description: 'An Alien Hand Supplementary Reader' },
        { name: 'Bringing Up Kari', description: 'An Alien Hand Supplementary Reader' },
        { name: 'Golu Grows a Nose', description: 'An Alien Hand Supplementary Reader' },
        { name: 'Chandni', description: 'An Alien Hand Supplementary Reader' },
        { name: 'The Desert', description: 'An Alien Hand Supplementary Reader' },
        { name: 'The Cop And The Anthem', description: 'An Alien Hand Supplementary Reader' },
        { name: 'I Want Something In A Cage', description: 'An Alien Hand Supplementary Reader' },
        { name: 'The Bear Story', description: 'An Alien Hand Supplementary Reader' },
        { name: 'A Tiger In The House', description: 'An Alien Hand Supplementary Reader' },
        { name: 'An Alien Hand', description: 'An Alien Hand Supplementary Reader' },
      ],
      'Hindi': [
        { name: 'Vah Chidiya Jo', description: 'वह चिड़िया जो (Vasant)' },
        { name: 'Bachpan', description: 'बचपन (Vasant)' },
        { name: 'Naadaan Dost', description: 'नादान दोस्त (Vasant)' },
        { name: 'Chand se Thodi-si Gappein', description: 'चाँद से थोड़ी-सी गप्पें (Vasant)' },
        { name: 'Aksharon Ka Mahatv', description: 'अक्षरों का महत्व (Vasant)' },
        { name: 'Paar Nazar Ke', description: 'पार नज़र के (Vasant)' },
        { name: 'Saathi Haath Badhaana', description: 'साथी हाथ बढ़ाना (Vasant)' },
        { name: 'Aise-Aise', description: 'ऐसे-ऐसे (Vasant)' },
        { name: 'Tikat Albam', description: 'टिकट अलबम (Vasant)' },
        { name: 'Jhansi Ki Rani', description: 'झाँसी की रानी (Vasant)' },
        { name: 'Jo Dekhkar Bhi Nahin Dekhte', description: 'जो देखकर भी नहीं देखते (Vasant)' },
        { name: 'Sansar Pustak Hai', description: 'संसार पुस्तक है (Vasant)' },
        { name: 'Main Sabse Chhoti Hoon', description: 'मैं सबसे छोटी होऊँ (Vasant)' },
        { name: 'Lokageet', description: 'लोकगीत (Vasant)' },
        { name: 'Naukar', description: 'नौकर (Vasant)' },
        { name: 'Van Ke Maarg Mein', description: 'वन के मार्ग में (Vasant)' },
        { name: 'Saans-Saans Mein Baans', description: 'साँस-साँस में बाँस (Vasant)' },
      ],
    },
    '8': {
      'Mathematics': [
        { name: 'Rational Numbers', description: 'Properties and operations of rational numbers.' },
        { name: 'Linear Equations in One Variable', description: 'Solving linear equations with one variable.' },
        { name: 'Understanding Quadrilaterals', description: 'Types and properties of quadrilaterals.' },
        { name: 'Practical Geometry', description: 'Construction of geometrical figures.' },
        { name: 'Data Handling', description: 'Collecting, organizing, and interpreting data.' },
        { name: 'Squares and Square Roots', description: 'Finding squares and square roots of numbers.' },
        { name: 'Cubes and Cube Roots', description: 'Finding cubes and cube roots of numbers.' },
        { name: 'Comparing Quantities', description: 'Ratio, proportion, percentage, and profit/loss.' },
        { name: 'Algebraic Expressions and Identities', description: 'Operations with algebraic expressions and identities.' },
        { name: 'Visualising Solid Shapes', description: 'Understanding 2D and 3D shapes.' },
        { name: 'Mensuration', description: 'Area, perimeter, and volume of various shapes.' },
        { name: 'Exponents and Powers', description: 'Understanding exponents and powers.' },
        { name: 'Direct and Inverse Proportions', description: 'Solving problems related to direct and inverse proportions.' },
        { name: 'Factorisation', description: 'Factorizing algebraic expressions.' },
        { name: 'Introduction to Graphs', description: 'Plotting and interpreting graphs.' },
        { name: 'Playing with Numbers', description: 'Number puzzles and divisibility rules.' },
      ],
      'Science': [
        { name: 'Crop Production and Management', description: 'Practices for growing and managing crops.' },
        { name: 'Microorganisms – Friend and Foe', description: 'Beneficial and harmful microorganisms.' },
        { name: 'Synthetic Fibres and Plastics', description: 'Types and properties of synthetic materials.' },
        { name: 'Materials – Metals and Non-Metals', description: 'Properties and uses of metals and non-metals.' },
        { name: 'Coal and Petroleum', description: 'Sources and uses of fossil fuels.' },
        { name: 'Combustion and Flame', description: 'Understanding burning and flames.' },
        { name: 'Conservation of Plants and Animals', description: 'Importance of preserving biodiversity.' },
        { name: 'Cell – Structure and Functions', description: 'Basic unit of life and its functions.' },
        { name: 'Reproduction in Animals', description: 'Modes of reproduction in animals.' },
        { name: 'Reaching the Age of Adolescence', description: 'Changes during adolescence.' },
        { name: 'Force and Pressure', description: 'Concepts of force, pressure, and their effects.' },
        { name: 'Friction', description: 'Understanding friction and its effects.' },
        { name: 'Sound', description: 'Production and propagation of sound.' },
        { name: 'Chemical Effects of Electric Current', description: 'Effects of electric current on substances.' },
        { name: 'Some Natural Phenomena', description: 'Lightning, earthquakes, and other natural events.' },
        { name: 'Light', description: 'Reflection, refraction, and dispersion of light.' },
        { name: 'Stars and the Solar System', description: 'Celestial bodies and their movements.' },
        { name: 'Pollution of Air and Water', description: 'Causes and effects of environmental pollution.' },
      ],
      'Social Science': [
        { name: 'How, When and Where', description: 'Understanding historical periods and sources.' },
        { name: 'From Trade to Territory', description: 'Expansion of British power in India.' },
        { name: 'Ruling the Countryside', description: 'British administration and policies in rural areas.' },
        { name: 'Tribals, Dikus and the Vision of a Golden Age', description: 'Tribal societies and their struggles.' },
        { name: 'When People Rebel', description: 'Revolts against British rule.' },
        { name: 'Colonialism and the City', description: 'Impact of colonialism on Indian cities.' },
        { name: 'Weavers, Iron Smelters and Factory Owners', description: 'Industrial changes in India.' },
        { name: 'Civilising the “Native”, Educating the Nation', description: 'British education policies in India.' },
        { name: 'Women, Caste, and Reform', description: 'Social reforms and movements in India.' },
        { name: 'The Changing World of Visual Arts', description: 'Development of art and architecture in colonial India.' },
        { name: 'The Making of the National Movement', description: 'Rise of nationalism and freedom struggle.' },
        { name: 'India After Independence', description: 'Challenges and developments in post-independence India.' },
        { name: 'Resources', description: 'Types and distribution of natural resources.' },
        { name: 'Land, Soil, Water, Natural Vegetation and Wildlife Resources', description: 'Importance and conservation of natural resources.' },
        { name: 'Mineral and Power Resources', description: 'Types and uses of minerals and energy resources.' },
        { name: 'Agriculture', description: 'Types of farming and agricultural practices.' },
        { name: 'Industries', description: 'Types of industries and their distribution.' },
        { name: 'Human Resource', description: 'Population distribution, density, and growth.' },
        { name: 'The Indian Constitution', description: 'Key features of the Indian Constitution.' },
        { name: 'Understanding Secularism', description: 'Concept of secularism in India.' },
        { name: 'Why Do We Need a Parliament?', description: 'Role and functions of the Indian Parliament.' },
        { name: 'Understanding Laws', description: 'Importance and types of laws.' },
        { name: 'Judiciary', description: 'Role and functions of the Indian judiciary.' },
        { name: 'Understanding Our Criminal Justice System', description: 'Working of the criminal justice system.' },
        { name: 'Understanding Marginalisation', description: 'Issues faced by marginalized communities.' },
        { name: 'Confronting Marginalisation', description: 'Efforts to address marginalization.' },
        { name: 'Public Facilities', description: 'Access to basic public services.' },
        { name: 'Law and Social Justice', description: 'Laws and policies for social justice.' },
      ],
      'English': [
        { name: 'The Best Christmas Present in the World', description: 'Honeydew - Prose' },
        { name: 'The Ant and the Cricket', description: 'Honeydew - Poem' },
        { name: 'The Tsunami', description: 'Honeydew - Prose' },
        { name: 'Geography Lesson', description: 'Honeydew - Poem' },
        { name: 'Glimpses of the Past', description: 'Honeydew - Prose' },
        { name: 'Macavity: The Mystery Cat', description: 'Honeydew - Poem' },
        { name: 'Bepin Choudhury\'s Lapse of Memory', description: 'Honeydew - Prose' },
        { name: 'The Last Bargain', description: 'Honeydew - Poem' },
        { name: 'The Summit Within', description: 'Honeydew - Prose' },
        { name: 'The School Boy', description: 'Honeydew - Poem' },
        { name: 'This is Jody\'s Fawn', description: 'Honeydew - Prose' },
        { name: 'The Duck and the Kangaroo', description: 'Honeydew - Poem' },
        { name: 'A Visit to Cambridge', description: 'Honeydew - Prose' },
        { name: 'When I Set Out for Lyonnesse', description: 'Honeydew - Poem' },
        { name: 'A Short Monsoon Diary', description: 'Honeydew - Prose' },
        { name: 'On the Grasshopper and Cricket', description: 'Honeydew - Poem' },
        { name: 'The Great Stone Face – I', description: 'Honeydew - Prose' },
        { name: 'The Great Stone Face – II', description: 'Honeydew - Prose' },
        { name: 'How the Camel Got His Hump', description: 'It So Happened' },
        { name: 'Children at Work', description: 'It So Happened' },
        { name: 'The Selfish Giant', description: 'It So Happened' },
        { name: 'The Treasure Within', description: 'It So Happened' },
        { name: 'Princess September', description: 'It So Happened' },
        { name: 'The Fight', description: 'It So Happened' },
        { name: 'Jalebis', description: 'It So Happened' },
        { name: 'Ancient Education System of India', description: 'It So Happened' },
      ],
      'Hindi': [
        { name: 'Vah Chidiya Jo', description: 'वह चिड़िया जो (Vasant)' },
        { name: 'Bachpan', description: 'बचपन (Vasant)' },
        { name: 'Naadaan Dost', description: 'नादान दोस्त (Vasant)' },
        { name: 'Chand se Thodi-si Gappein', description: 'चाँद से थोड़ी-सी गप्पें (Vasant)' },
        { name: 'Aksharon Ka Mahatv', description: 'अक्षरों का महत्व (Vasant)' },
        { name: 'Paar Nazar Ke', description: 'पार नज़र के (Vasant)' },
        { name: 'Saathi Haath Badhaana', description: 'साथी हाथ बढ़ाना (Vasant)' },
        { name: 'Aise-Aise', description: 'ऐसे-ऐसे (Vasant)' },
        { name: 'Tikat Albam', description: 'टिकट अलबम (Vasant)' },
        { name: 'Jhansi Ki Rani', description: 'झाँसी की रानी (Vasant)' },
        { name: 'Jo Dekhkar Bhi Nahin Dekhte', description: 'जो देखकर भी नहीं देखते (Vasant)' },
        { name: 'Sansar Pustak Hai', description: 'संसार पुस्तक है (Vasant)' },
        { name: 'Main Sabse Chhoti Hoon', description: 'मैं सबसे छोटी होऊँ (Vasant)' },
        { name: 'Lokageet', description: 'लोकगीत (Vasant)' },
        { name: 'Naukar', description: 'नौकर (Vasant)' },
        { name: 'Van Ke Maarg Mein', description: 'वन के मार्ग में (Vasant)' },
        { name: 'Saans-Saans Mein Baans', description: 'साँस-साँस में बाँस (Vasant)' },
      ],
    },
    '9': {
      'Mathematics': [
        { name: 'Rational Numbers', description: 'Properties and operations of rational numbers.' },
        { name: 'Polynomials', description: 'Algebraic expressions and their properties.' },
        { name: 'Coordinate Geometry', description: 'Introduction to coordinate system and plotting points.' },
        { name: 'Linear Equations in Two Variables', description: 'Solving linear equations with two variables.' },
        { name: 'Introduction to Euclid\'s Geometry', description: 'Basic concepts of Euclidean geometry.' },
        { name: 'Lines and Angles', description: 'Properties of lines and angles.' },
        { name: 'Triangles', description: 'Types and properties of triangles.' },
        { name: 'Quadrilaterals', description: 'Types and properties of quadrilaterals.' },
        { name: 'Areas of Parallelograms and Triangles', description: 'Calculating areas of parallelograms and triangles.' },
        { name: 'Circles', description: 'Properties of circles and related theorems.' },
        { name: 'Constructions', description: 'Geometric constructions using ruler and compass.' },
        { name: 'Heron\'s Formula', description: 'Calculating area of triangles using Heron\'s formula.' },
        { name: 'Surface Areas and Volumes', description: 'Calculating surface areas and volumes of 3D shapes.' },
        { name: 'Statistics', description: 'Collection, organization, and interpretation of data.' },
        { name: 'Probability', description: 'Introduction to probability and its applications.' },
      ],
      'Science': [
        { name: 'Matter in Our Surroundings', description: 'States of matter and their properties.' },
        { name: 'Is Matter Around Us Pure?', description: 'Classification of matter and separation techniques.' },
        { name: 'Atoms and Molecules', description: 'Basic concepts of atoms, molecules, and chemical reactions.' },
        { name: 'Structure of the Atom', description: 'Atomic models and subatomic particles.' },
        { name: 'The Fundamental Unit of Life', description: 'Cell structure and functions.' },
        { name: 'Tissues', description: 'Types of tissues and their functions.' },
        { name: 'Diversity in Living Organisms', description: 'Classification of plants and animals.' },
        { name: 'Motion', description: 'Types of motion and related concepts.' },
        { name: 'Force and Laws of Motion', description: 'Newton\'s laws of motion and their applications.' },
        { name: 'Gravitation', description: 'Universal law of gravitation and its effects.' },
        { name: 'Work and Energy', description: 'Concepts of work, energy, and power.' },
        { name: 'Sound', description: 'Production, propagation, and characteristics of sound.' },
        { name: 'Why Do We Fall Ill', description: 'Causes of diseases and their prevention.' },
        { name: 'Natural Resources', description: 'Types and importance of natural resources.' },
        { name: 'Improvement in Food Resources', description: 'Methods for enhancing food production.' },
      ],
      'Social Science': [
        { name: 'The French Revolution', description: 'Causes, events, and impact of the French Revolution. (History)' },
        { name: 'Socialism in Europe and the Russian Revolution', description: 'Rise of socialism and the Russian Revolution. (History)' },
        { name: 'Nazism and the Rise of Hitler', description: 'Rise of Nazism and Hitler\'s ideology. (History)' },
        { name: 'Forest Society and Colonialism', description: 'Impact of colonialism on forest communities. (History)' },
        { name: 'Pastoralists in the Modern World', description: 'Life of pastoral communities in modern times. (History)' },
        { name: 'India – Size and Location', description: 'Geographical features and location of India. (Geography)' },
        { name: 'Physical Features of India', description: 'Major physical divisions of India. (Geography)' },
        { name: 'Drainage', description: 'River systems of India. (Geography)' },
        { name: 'Climate', description: 'Climatic conditions and factors affecting climate in India. (Geography)' },
        { name: 'Natural Vegetation and Wildlife', description: 'Types of vegetation and wildlife in India. (Geography)' },
        { name: 'Population', description: 'Population distribution, density, and growth in India. (Geography)' },
        { name: 'What is Democracy? Why Democracy?', description: 'Understanding democracy and its features. (Political Science)' },
        { name: 'Constitutional Design', description: 'Making of the Indian Constitution. (Political Science)' },
        { name: 'Electoral Politics', description: 'Electoral system in India. (Political Science)' },
        { name: 'Working of Institutions', description: 'Functioning of government institutions. (Political Science)' },
        { name: 'Democratic Rights', description: 'Fundamental rights and their importance. (Political Science)' },
        { name: 'The Story of Village Palampur', description: 'Introduction to basic economic concepts. (Economics)' },
        { name: 'People as Resource', description: 'Population as a human capital. (Economics)' },
        { name: 'Poverty as a Challenge', description: 'Causes and consequences of poverty. (Economics)' },
        { name: 'Food Security in India', description: 'Ensuring food availability and accessibility. (Economics)' },
      ],
      'English': [
        { name: 'The Fun They Had', description: 'Beehive - Prose' },
        { name: 'The Sound of Music', description: 'Beehive - Prose' },
        { name: 'The Little Girl', description: 'Beehive - Prose' },
        { name: 'A Truly Beautiful Mind', description: 'Beehive - Prose' },
        { name: 'The Snake and the Mirror', description: 'Beehive - Prose' },
        { name: 'My Childhood', description: 'Beehive - Prose' },
        { name: 'Packing', description: 'Beehive - Prose' },
        { name: 'Reach for the Top', description: 'Beehive - Prose' },
        { name: 'The Bond of Love', description: 'Beehive - Prose' },
        { name: 'Kathmandu', description: 'Beehive - Prose' },
        { name: 'If I Were You', description: 'Beehive - Prose' },
        { name: 'The Road Not Taken', description: 'Beehive - Poem' },
        { name: 'Wind', description: 'Beehive - Poem' },
        { name: 'Rain on the Roof', description: 'Beehive - Poem' },
        { name: 'The Lake Isle of Innisfree', description: 'Beehive - Poem' },
        { name: 'A Legend of the Northland', description: 'Beehive - Poem' },
        { name: 'No Men Are Foreign', description: 'Beehive - Poem' },
        { name: 'The Duck and the Kangaroo', description: 'Beehive - Poem' },
        { name: 'On Killing a Tree', description: 'Beehive - Poem' },
        { name: 'The Snake Trying', description: 'Beehive - Poem' },
        { name: 'A Slumber Did My Spirit Seal', description: 'Beehive - Poem' },
        { name: 'The Lost Child', description: 'Moments' },
        { name: 'The Adventures of Toto', description: 'Moments' },
        { name: 'Iswaran the Storyteller', description: 'Moments' },
        { name: 'In the Kingdom of Fools', description: 'Moments' },
        { name: 'The Happy Prince', description: 'Moments' },
        { name: 'Weathering the Storm in Ersama', description: 'Moments' },
        { name: 'The Last Leaf', description: 'Moments' },
        { name: 'A House Is Not a Home', description: 'Moments' },
        { name: 'The Accidental Tourist', description: 'Moments' },
        { name: 'The Beggar', description: 'Moments' },
      ],
      'Hindi': [
        { name: 'दो बैलों की कथा', description: 'Kshitij' },
        { name: 'ल्हासा की ओर', description: 'Kshitij' },
        { name: 'उपभोक्तावाद की संस्कृति', description: 'Kshitij' },
        { name: 'साँवले सपनों की याद', description: 'Kshitij' },
        { name: 'नाना साहब की पुत्री देवी मैना को भस्म कर दिया गया', description: 'Kshitij' },
        { name: 'प्रेमचंद के फटे जूते', description: 'Kshitij' },
        { name: 'मेरे बचपन के दिन', description: 'Kshitij' },
        { name: 'एक कुत्ता और एक मैना', description: 'Kshitij' },
        { name: 'साखियाँ एवं सबद', description: 'Kshitij' },
        { name: 'वाख', description: 'Kshitij' },
        { name: 'सवैये', description: 'Kshitij' },
        { name: 'कैदी और कोकिला', description: 'Kshitij' },
        { name: 'ग्राम श्री', description: 'Kshitij' },
        { name: 'चंद्र गहना से लौटती बेर', description: 'Kshitij' },
        { name: 'मेघ आए', description: 'Kshitij' },
        { name: 'यमराज की दिशा', description: 'Kshitij' },
        { name: 'बच्चे काम पर जा रहे हैं', description: 'Kshitij' },
        { name: 'धूल', description: 'Sparsh' },
        { name: 'दुःख का अधिकार', description: 'Sparsh' },
        { name: 'एवरेस्ट : मेरी शिखर यात्रा', description: 'Sparsh' },
        { name: 'तुम कब जाओगे, अतिथि', description: 'Sparsh' },
        { name: 'वैज्ञानिक चेतना के वाहक : चन्द्र शेखर वेंकट रामन', description: 'Sparsh' },
        { name: 'कीचड़ का काव्य', description: 'Sparsh' },
        { name: 'धर्म की आड़', description: 'Sparsh' },
        { name: 'शक्र तारे के समान', description: 'Sparsh' },
        { name: 'आदमीनामा', description: 'Sparsh' },
        { name: 'एक फूल की चाह', description: 'Sparsh' },
        { name: 'गीत अगीत', description: 'Sparsh' },
        { name: 'अग्नि पथ', description: 'Sparsh' },
        { name: 'नए इलाके में – खुशबु रचते हैं हाथ', description: 'Sparsh' },
      ],
    },
    '10': {
      'Mathematics': [
        { name: 'Real Numbers', description: 'Properties and operations of real numbers.' },
        { name: 'Polynomials', description: 'Algebraic expressions and their properties.' },
        { name: 'Pair of Linear Equations in Two Variables', description: 'Solving linear equations with two variables.' },
        { name: 'Quadratic Equations', description: 'Solving quadratic equations.' },
        { name: 'Arithmetic Progressions', description: 'Sequences and series.' },
        { name: 'Triangles', description: 'Properties of triangles and similarity.' },
        { name: 'Coordinate Geometry', description: 'Introduction to coordinate system and plotting points.' },
        { name: 'Introduction to Trigonometry', description: 'Basic concepts of trigonometry.' },
        { name: 'Some Applications of Trigonometry', description: 'Solving problems using trigonometric ratios.' },
        { name: 'Circles', description: 'Properties of circles and related theorems.' },
        { name: 'Areas Related to Circles', description: 'Calculating areas of circles and sectors.' },
        { name: 'Surface Areas and Volumes', description: 'Calculating surface areas and volumes of 3D shapes.' },
        { name: 'Statistics', description: 'Collection, organization, and interpretation of data.' },
        { name: 'Probability', description: 'Introduction to probability and its applications.' },
      ],
      'Science': [
        { name: 'Chemical Reactions and Equations', description: 'Types of chemical reactions and balancing equations.' },
        { name: 'Acids, Bases and Salts', description: 'Properties and uses of acids, bases, and salts.' },
        { name: 'Metals and Non-metals', description: 'Properties and uses of metals and non-metals.' },
        { name: 'Carbon and its Compounds', description: 'Properties and reactions of carbon compounds.' },
        { name: 'Life Processes', description: 'Basic life processes in living organisms.' },
        { name: 'Control and Coordination', description: 'Nervous and hormonal control in living organisms.' },
        { name: 'How do Organisms Reproduce?', description: 'Modes of reproduction in plants and animals.' },
        { name: 'Heredity and Evolution', description: 'Principles of heredity and evolution.' },
        { name: 'Light – Reflection and Refraction', description: 'Properties of light and optical phenomena.' },
        { name: 'The Human Eye and the Colourful World', description: 'Structure and functioning of the human eye.' },
        { name: 'Electricity', description: 'Concepts of electric current, voltage, and resistance.' },
        { name: 'Magnetic Effects of Electric Current', description: 'Magnetic effects of electric current and electromagnetic induction.' },
        { name: 'Our Environment', description: 'Components of the environment and environmental problems.' },
      ],
      'Social Science': [
        { name: 'The Rise of Nationalism in Europe', description: 'Causes and impact of nationalism in Europe. (History)' },
        { name: 'The Nationalist Movement in Indo-China', description: 'Nationalist movements in Vietnam. (History)' },
        { name: 'Nationalism in India', description: 'Rise of nationalism and freedom struggle in India. (History)' },
        { name: 'The Making of a Global World', description: 'Globalization and its historical context. (History)' },
        { name: 'The Age of Industrialisation', description: 'Industrialization in Europe and its impact. (History)' },
        { name: 'Work, Life and Leisure', description: 'Social and cultural changes in urban areas. (History)' },
        { name: 'Print Culture and the Modern World', description: 'Impact of print technology on society. (History)' },
        { name: 'Novels, Society and History', description: 'Role of novels in reflecting social changes. (History)' },
        { name: 'Resource and Development', description: 'Types and distribution of natural resources. (Geography)' },
        { name: 'Forest and Wildlife Resources', description: 'Importance and conservation of forest and wildlife. (Geography)' },
        { name: 'Water Resources', description: 'Importance and management of water resources. (Geography)' },
        { name: 'Agriculture', description: 'Types of farming and agricultural practices. (Geography)' },
        { name: 'Minerals and Energy Resources', description: 'Types and uses of minerals and energy resources. (Geography)' },
        { name: 'Manufacturing Industries', description: 'Types of industries and their distribution. (Geography)' },
        { name: 'Lifelines of National Economy', description: 'Importance of transport and communication. (Geography)' },
        { name: 'Power Sharing', description: 'Distribution of power in a democracy. (Political Science)' },
        { name: 'Federalism', description: 'Features of federalism in India. (Political Science)' },
        { name: 'Gender, Religion and Caste', description: 'Social divisions and inequalities. (Political Science)' },
        { name: 'Political Parties', description: 'Role and functions of political parties. (Political Science)' },
        { name: 'Outcomes of Democracy', description: 'Assessment of democratic achievements. (Political Science)' },
        { name: 'Development', description: 'Concept of development and its indicators. (Economics)' },
        { name: 'Sectors of the Indian Economy', description: 'Classification of economic activities. (Economics)' },
        { name: 'Money and Credit', description: 'Role of money and credit in the economy. (Economics)' },
        { name: 'Globalisation and the Indian Economy', description: 'Impact of globalization on India. (Economics)' },
        { name: 'Consumer Rights', description: 'Rights and responsibilities of consumers. (Economics)' },
      ],
      'English': [
        { name: 'A Letter to God', description: 'First Flight - Prose' },
        { name: 'Nelson Mandela: Long Walk to Freedom', description: 'First Flight - Prose' },
        { name: 'Two Stories about Flying', description: 'First Flight - Prose' },
        { name: 'From the Diary of Anne Frank', description: 'First Flight - Prose' },
        { name: 'The Hundred Dresses – I', description: 'First Flight - Prose' },
        { name: 'The Hundred Dresses – II', description: 'First Flight - Prose' },
        { name: 'Glimpses of India', description: 'First Flight - Prose' },
        { name: 'Mijbil the Otter', description: 'First Flight - Prose' },
        { name: 'Madam Rides the Bus', description: 'First Flight - Prose' },
        { name: 'The Sermon at Benares', description: 'First Flight - Prose' },
        { name: 'The Proposal', description: 'First Flight - Prose' },
        { name: 'Dust of Snow', description: 'First Flight - Poem' },
        { name: 'Fire and Ice', description: 'First Flight - Poem' },
        { name: 'A Tiger in the Zoo', description: 'First Flight - Poem' },
        { name: 'How to Tell Wild Animals', description: 'First Flight - Poem' },
        { name: 'The Ball Poem', description: 'First Flight - Poem' },
        { name: 'Amanda!', description: 'First Flight - Poem' },
        { name: 'Animals', description: 'First Flight - Poem' },
        { name: 'The Trees', description: 'First Flight - Poem' },
        { name: 'Fog', description: 'First Flight - Poem' },
        { name: 'The Tale of Custard the Dragon', description: 'First Flight - Poem' },
        { name: 'For Anne Gregory', description: 'First Flight - Poem' },
        { name: 'A Triumph of Surgery', description: 'Footprints without Feet' },
        { name: 'The Thief\'s Story', description: 'Footprints without Feet' },
        { name: 'The Midnight Visitor', description: 'Footprints without Feet' },
        { name: 'A Question of Trust', description: 'Footprints without Feet' },
        { name: 'Footprints without Feet', description: 'Footprints without Feet' },
        { name: 'The Making of a Scientist', description: 'Footprints without Feet' },
        { name: 'The Necklace', description: 'Footprints without Feet' },
        { name: 'The Hack Driver', description: 'Footprints without Feet' },
        { name: 'Bholi', description: 'Footprints without Feet' },
        { name: 'The Book that Saved the Earth', description: 'Footprints without Feet' },
      ],
      'Hindi': [
        { name: 'Vah Chidiya Jo', description: 'वह चिड़िया जो (Vasant)' },
        { name: 'Bachpan', description: 'बचपन (Vasant)' },
        { name: 'Naadaan Dost', description: 'नादान दोस्त (Vasant)' },
        { name: 'Chand se Thodi-si Gappein', description: 'चाँद से थोड़ी-सी गप्पें (Vasant)' },
        { name: 'Aksharon Ka Mahatv', description: 'अक्षरों का महत्व (Vasant)' },
        { name: 'Paar Nazar Ke', description: 'पार नज़र के (Vasant)' },
        { name: 'Saathi Haath Badhaana', description: 'साथी हाथ बढ़ाना (Vasant)' },
        { name: 'Aise-Aise', description: 'ऐसे-ऐसे (Vasant)' },
        { name: 'Tikat Albam', description: 'टिकट अलबम (Vasant)' },
        { name: 'Jhansi Ki Rani', description: 'झाँसी की रानी (Vasant)' },
        { name: 'Jo Dekhkar Bhi Nahin Dekhte', description: 'जो देखकर भी नहीं देखते (Vasant)' },
        { name: 'Sansar Pustak Hai', description: 'संसार पुस्तक है (Vasant)' },
        { name: 'Main Sabse Chhoti Hoon', description: 'मैं सबसे छोटी होऊँ (Vasant)' },
        { name: 'Lokageet', description: 'लोकगीत (Vasant)' },
        { name: 'Naukar', description: 'नौकर (Vasant)' },
        { name: 'Van Ke Maarg Mein', description: 'वन के मार्ग में (Vasant)' },
        { name: 'Saans-Saans Mein Baans', description: 'साँस-साँस में बाँस (Vasant)' },
      ],
    },
    '11': {
      'Physics': [
        { name: 'Physical World', description: 'Introduction to physics and its scope.' },
        { name: 'Units and Measurements', description: 'Systems of units and measurement techniques.' },
        { name: 'Motion in a Straight Line', description: 'Kinematics of motion in one dimension.' },
        { name: 'Motion in a Plane', description: 'Kinematics of motion in two and three dimensions.' },
        { name: 'Laws of Motion', description: "Newton's laws of motion and their applications." },
        { name: 'Work, Energy and Power', description: 'Concepts of work, energy, and power.' },
        { name: 'System of Particles and Rotational Motion', description: 'Dynamics of rigid bodies.' },
        { name: 'Gravitation', description: 'Universal law of gravitation and its applications.' },
        { name: 'Mechanical Properties Of Solids', description: 'Elasticity and properties of solids.' },
        { name: 'Mechanical Properties Of Fluids', description: 'Properties of fluids and fluid dynamics.' },
        { name: 'Thermal Properties of Matter', description: 'Heat, temperature, and thermal expansion.' },
        { name: 'Thermodynamics', description: 'Laws of thermodynamics and heat engines.' },
        { name: 'Kinetic Theory', description: 'Kinetic theory of gases.' },
        { name: 'Oscillations', description: 'Simple harmonic motion and oscillations.' },
        { name: 'Waves', description: 'Types of waves and wave phenomena.' },
      ],
      'Chemistry': [
        { name: 'Some Basic Concepts of Chemistry', description: 'Fundamental laws of chemistry and stoichiometry.' },
        { name: 'Structure of Atom', description: 'Atomic models and quantum mechanics.' },
        { name: 'Classification of Elements and Periodicity in Properties', description: 'Periodic table and periodic trends.' },
        { name: 'Chemical Bonding and Molecular Structure', description: 'Types of chemical bonds and molecular shapes.' },
        { name: 'Thermodynamics', description: 'Laws of thermodynamics and chemical energetics.' },
        { name: 'Equilibrium', description: 'Chemical and ionic equilibrium.' },
        { name: 'Redox Reactions', description: 'Oxidation, reduction, and redox reactions.' },
        { name: 'Organic Chemistry – Some Basic Principles & Techniques', description: 'Purification and characterization of organic compounds.' },
        { name: 'Hydrocarbons', description: 'Classification, nomenclature, and reactions of hydrocarbons.' },
      ],
      'Biology': [
        { name: 'The Living World', description: 'Characteristics of living organisms and biodiversity.' },
        { name: 'Biological Classification', description: 'Classification of living organisms.' },
        { name: 'Plant Kingdom', description: 'Classification of plants.' },
        { name: 'Animal Kingdom', description: 'Classification of animals.' },
        { name: 'Morphology of Flowering Plants', description: 'External features of flowering plants.' },
        { name: 'Anatomy of Flowering Plants', description: 'Internal structure of flowering plants.' },
        { name: 'Structural Organisation in Animals', description: 'Tissues and organ systems in animals.' },
        { name: 'Cell: The Unit of Life', description: 'Cell structure and functions.' },
        { name: 'Biomolecules', description: 'Structure and functions of biomolecules.' },
        { name: 'Cell Cycle and Cell Division', description: 'Cell division and its regulation.' },
        { name: 'Photosynthesis in Higher Plants', description: 'Process of photosynthesis.' },
        { name: 'Respiration in Plants', description: 'Cellular respiration in plants.' },
        { name: 'Plant Growth and Development', description: 'Plant hormones and growth regulation.' },
        { name: 'Breathing and Exchange of Gases', description: 'Respiration in humans.' },
        { name: 'Body Fluids and Circulation', description: 'Composition and circulation of blood.' },
        { name: 'Excretory Products and their Elimination', description: 'Excretion in humans.' },
        { name: 'Locomotion and Movement', description: 'Types of movement and skeletal system.' },
        { name: 'Neural Control and Coordination', description: 'Nervous system and coordination.' },
        { name: 'Chemical Coordination and Integration', description: 'Endocrine system and hormones.' },
      ],
      'Mathematics': [
        { name: 'Sets', description: 'Basic concepts of sets and set operations.' },
        { name: 'Relations and Functions', description: 'Types of relations and functions.' },
        { name: 'Trigonometric Functions', description: 'Trigonometric ratios and identities.' },
        { name: 'Principle of Mathematical Induction', description: 'Proof by mathematical induction.' },
        { name: 'Complex Numbers and Quadratic Equations', description: 'Complex numbers and solving quadratic equations.' },
        { name: 'Linear Inequalities', description: 'Solving linear inequalities.' },
        { name: 'Permutations and Combinations', description: 'Counting principles and arrangements.' },
        { name: 'Binomial Theorem', description: 'Expansion of binomial expressions.' },
        { name: 'Sequences and Series', description: 'Arithmetic and geometric progressions.' },
        { name: 'Straight Lines', description: 'Equations of straight lines.' },
        { name: 'Conic Sections', description: 'Properties of conic sections (circle, ellipse, parabola, hyperbola).' },
        { name: 'Introduction to Three Dimensional Geometry', description: 'Coordinates in 3D space.' },
        { name: 'Limits and Derivatives', description: 'Concepts of limits and derivatives.' },
        { name: 'Mathematical Reasoning', description: 'Logic and mathematical statements.' },
        { name: 'Statistics', description: 'Measures of central tendency and dispersion.' },
        { name: 'Probability', description: 'Introduction to probability and its applications.' },
      ],
      'Business Studies': [
        { name: 'Nature and Significance of Management', description: 'Introduction to management.' },
        { name: 'Principles of Management', description: 'Principles of scientific management and Fayol\'s principles.' },
        { name: 'Business Environment', description: 'Dimensions of business environment.' },
        { name: 'Planning', description: 'Steps in planning process.' },
        { name: 'Organising', description: 'Steps in organizing process.' },
        { name: 'Staffing', description: 'Steps in staffing process.' },
        { name: 'Directing', description: 'Elements of directing.' },
        { name: 'Controlling', description: 'Steps in controlling process.' },
        { name: 'Financial Management', description: 'Objectives and functions of financial management.' },
        { name: 'Financial Markets', description: 'Money market and capital market.' },
        { name: 'Marketing', description: 'Marketing mix and marketing management.' },
        { name: 'Consumer Protection', description: 'Consumer rights and responsibilities.' },
      ],
      'Accountancy': [
        { name: 'Introduction to Accounting', description: 'Basics of accounting, its objectives, and its role in business.' },
        { name: 'Theory Base of Accounting', description: 'Fundamental accounting principles, concepts, and standards.' },
        { name: 'Recording of Transactions - I', description: 'Initial steps of recording business transactions.' },
        { name: 'Recording of Transactions - II', description: 'Continues to build on the process of recording transactions.' },
        { name: 'Bank Reconciliation Statement', description: 'Reconcile differences between the cash book and the bank passbook.' },
        { name: 'Trial Balance and Rectification of Errors', description: 'Preparing the trial balance and correcting any accounting errors.' },
        { name: 'Depreciation, Provisions, and Reserves', description: 'Concepts of depreciation and how to account for provisions and reserves.' },
        { name: 'Bill of Exchange', description: 'Accounting treatment for bills of exchange.' },
        { name: 'Financial Statements - I', description: 'Introduction to the preparation of financial statements.' },
        { name: 'Financial Statements - II', description: 'Continues with more advanced aspects of financial statements.' },
        { name: 'Accounts from Incomplete Records', description: 'Prepare accounts when records are not fully maintained.' },
        { name: 'Applications of Computers in Accounting', description: 'Explores how computers are used in the accounting process.' },
        { name: 'Computerised Accounting System', description: 'Understanding of computerized accounting systems.' },
      ],
      'History': [
        { name: 'Bricks, Beads, and Bones (The Harappan Civilisation)', description: 'Harappan civilization.' },
        { name: 'Kinship, Caste, and Class (Early Societies)', description: 'Early societies.' },
        { name: 'Thinkers, Beliefs, and Buildings (Cultural Developments)', description: 'Cultural developments.' },
        { name: 'Through the Eyes of Travellers (Perceptions of Society)', description: 'Travellers\' accounts of Indian society.' },
        { name: 'Bhakti-Sufi Traditions (Changes in Religious Beliefs and Devotional Texts)', description: 'Religious beliefs and devotional texts.' },
        { name: 'An Imperial Capital: Vijayanagara', description: 'Vijayanagara Empire.' },
        { name: 'Peasants, Zamindars and the State (Agrarian Society and the Mughal Empire)', description: 'Agrarian society and the Mughal Empire.' },
        { name: 'Kings and Chronicles (The Mughal Courts)', description: 'Mughal courts.' },
        { name: 'Colonialism and the Countryside (Exploring Official Archives)', description: 'Colonialism and its impact on rural areas.' },
        { name: 'Rebels and the Raj (1857 Revolt and its Representations)', description: '1857 Revolt.' },
        { name: 'Colonial Cities (Urbanisation, Planning and Architecture)', description: 'Urbanization and architecture in colonial India.' },
        { name: 'Mahatma Gandhi and the Nationalist Movement (Civil Disobedience and Beyond)', description: 'Mahatma Gandhi\'s role in national movements.' },
        { name: 'Understanding Partition (Politics, Memories, Experiences)', description: 'Partition of India.' },
        { name: 'Framing the Constitution (The Beginning of a New Era)', description: 'Making of the Indian Constitution.' },
      ],
      'Geography': [
        { name: 'Human Geography: Nature and Scope', description: 'Introduction to human geography.' },
        { name: 'The World Population: Distribution, Density, and Growth', description: 'Population characteristics and trends.' },
        { name: 'Human Development', description: 'Concept and measurement of human development.' },
        { name: 'Primary Activities', description: 'Types of primary activities.' },
        { name: 'Secondary Activities', description: 'Types of secondary activities.' },
        { name: 'Tertiary and Quaternary Activities', description: 'Types of tertiary and quaternary activities.' },
        { name: 'Transport and Communication', description: 'Modes of transport and communication.' },
        { name: 'International Trade', description: 'Principles and patterns of international trade.' },
        { name: 'Population: Distribution, Density, Growth, and Composition', description: 'Population characteristics of India.' },
        { name: 'Human Settlements', description: 'Types and patterns of human settlements.' },
        { name: 'Land Resources and Agriculture', description: 'Land use and agricultural practices in India.' },
        { name: 'Water Resources', description: 'Water resources in India and their management.' },
        { name: 'Mineral and Energy Resources', description: 'Mineral and energy resources in India.' },
        { name: 'Planning and Sustainable Development in Indian Context', description: 'Regional planning and sustainable development.' },
        { name: 'Transport and Communication (India)', description: 'Modes of transport and communication in India.' },
        { name: 'International Trade (India)', description: 'International trade of India.' },
        { name: 'Geographical Perspective on Selected Issues and Problems', description: 'Environmental issues and problems.' },
      ],
      'Political Science': [
        { name: 'The Cold War Era', description: 'The Cold War and its impact on international politics.' },
        { name: 'The End of Bipolarity', description: 'End of Cold War and rise of new world order.' },
        { name: 'US Hegemony in World Politics', description: 'US dominance in the post-Cold War era.' },
        { name: 'Alternative Centers of Power', description: 'Rise of new power centers (e.g., EU, ASEAN, China).' },
        { name: 'Contemporary South Asia', description: 'Political developments in South Asia.' },
        { name: 'International Organizations', description: 'Role and functions of international organizations (e.g., UN).' },
        { name: 'Security in the Contemporary World', description: 'Traditional and non-traditional notions of security.' },
        { name: 'Environment and Natural Resources', description: 'Environmental concerns and resource management.' },
        { name: 'Globalisation', description: 'Economic, political, and cultural aspects of globalization.' },
        { name: 'Challenges of Nation-Building', description: 'Challenges faced by India after independence.' },
        { name: 'Era of One-Party Dominance', description: 'Congress dominance in Indian politics.' },
        { name: 'Politics of Planned Development', description: 'Planning and economic development in India.' },
        { name: 'India\'s External Relations', description: 'India\'s foreign policy.' },
        { name: 'Challenges to and Restoration of the Congress System', description: 'Challenges to Congress dominance and its restoration.' },
        { name: 'The Crisis of Democratic Order', description: 'Emergency and its impact on Indian democracy.' },
        { name: 'Regional Aspirations', description: 'Regional movements and autonomy demands.' },
        { name: 'Recent Developments in Indian Politics', description: 'Recent political developments in India.' },
      ],
      'Psychology': [
        { name: 'Variations in Psychological Attributes', description: 'Individual differences in psychological attributes.' },
        { name: 'Self and Personality', description: 'Concepts of self and theories of personality.' },
        { name: 'Meeting Life Challenges', description: 'Stress, coping, and well-being.' },
        { name: 'Psychological Disorders', description: 'Classification and causes of psychological disorders.' },
        { name: 'Therapeutic Approaches', description: 'Different approaches to psychotherapy.' },
        { name: 'Attitude and Social Cognition', description: 'Formation and change of attitudes.' },
        { name: 'Social Influence and Group Processes', description: 'Social influence and group dynamics.' },
      ],
      'Sociology': [
        { name: 'Introducing Indian Society', description: 'Introduction to Indian society.' },
        { name: 'The Demographic Structure of Indian Society', description: 'Population characteristics of India.' },
        { name: 'Social Institutions: Continuity and Change', description: 'Family, marriage, education, and religion.' },
        { name: 'Patterns of Social Inequality and Exclusion', description: 'Caste, class, and gender inequalities.' },
        { name: 'The Challenges of Cultural Diversity', description: 'Cultural diversity and its challenges.' },
        { name: 'Structural Change', description: 'Industrialization, urbanization, and social change.' },
        { name: 'Cultural Change', description: 'Modernization, Westernization, and Sanskritization.' },
        { name: 'Change and Development in Rural Society', description: 'Rural development and social change.' },
        { name: 'Change and Development in Industrial Society', description: 'Industrialization and its impact on society.' },
        { name: 'Social Movements', description: 'Types and theories of social movements.' },
      ],
    },
    '12': {
      'Physics': [
        { name: 'Electric Charges and Fields', description: 'Basic concepts of electric charges and fields.' },
        { name: 'Electrostatic Potential and Capacitance', description: 'Electric potential, potential energy, and capacitors.' },
        { name: 'Current Electricity', description: 'Electric current, Ohm\'s law, and circuits.' },
        { name: 'Moving Charges and Magnetism', description: 'Magnetic effects of current and magnetism.' },
        { name: 'Magnetism and Matter', description: 'Properties of magnetic materials.' },
        { name: 'Electromagnetic Induction', description: 'Faraday\'s laws and Lenz\'s law.' },
        { name: 'Alternating Current', description: 'AC circuits and power.' },
        { name: 'Electromagnetic Waves', description: 'Properties and spectrum of electromagnetic waves.' },
        { name: 'Ray Optics and Optical Instruments', description: 'Reflection, refraction, and optical instruments.' },
        { name: 'Wave Optics', description: 'Wave nature of light and interference.' },
        { name: 'Dual Nature of Radiation and Matter', description: 'Photoelectric effect and de Broglie waves.' },
        { name: 'Atoms', description: 'Bohr model and atomic spectra.' },
        { name: 'Nuclei', description: 'Nuclear structure and radioactivity.' },
        { name: 'Semiconductor Electronics: Materials, Devices and Simple Circuits', description: 'Semiconductors and their applications.' },
      ],
      'Chemistry': [
        { name: 'Solutions', description: 'Types of solutions and their properties.' },
        { name: 'Electrochemistry', description: 'Electrochemical cells and electrolysis.' },
        { name: 'Chemical Kinetics', description: 'Rates of reactions and reaction mechanisms.' },
        { name: 'd and f Block Elements', description: 'Properties of transition and inner transition elements.' },
        { name: 'Coordination Compounds', description: 'Structure and bonding in coordination compounds.' },
        { name: 'Haloalkanes and Haloarenes', description: 'Preparation, properties, and reactions of haloalkanes and haloarenes.' },
        { name: 'Alcohols, Phenols and Ethers', description: 'Preparation, properties, and reactions of alcohols, phenols, and ethers.' },
        { name: 'Aldehydes, Ketones and Carboxylic Acids', description: 'Preparation, properties, and reactions of aldehydes, ketones, and carboxylic acids.' },
        { name: 'Amines', description: 'Preparation, properties, and reactions of amines.' },
        { name: 'Biomolecules', description: 'Structure and functions of carbohydrates, proteins, nucleic acids, and vitamins.' },
      ],
      'Biology': [
        { name: 'Sexual Reproduction in Flowering Plants', description: 'Reproduction in angiosperms.' },
        { name: 'Human Reproduction', description: 'Reproductive system in humans.' },
        { name: 'Reproductive Health', description: 'Reproductive health issues and methods.' },
        { name: 'Principles of Inheritance and Variation', description: 'Mendelian genetics and inheritance patterns.' },
        { name: 'Molecular Basis of Inheritance', description: 'Structure and function of DNA and RNA.' },
        { name: 'Evolution', description: 'Theories and evidences of evolution.' },
        { name: 'Human Health and Diseases', description: 'Common human diseases and their prevention.' },
        { name: 'Microbes in Human Welfare', description: 'Role of microbes in various fields.' },
        { name: 'Biotechnology: Principles and Processes', description: 'Basic principles and techniques of biotechnology.' },
        { name: 'Biotechnology and Its Application', description: 'Applications of biotechnology in various fields.' },
        { name: 'Organisms and Populations', description: 'Ecological interactions and population dynamics.' },
        { name: 'Ecosystem', description: 'Structure and function of ecosystems.' },
        { name: 'Biodiversity and Conservation', description: 'Importance of biodiversity and its conservation.' },
      ],
            'Mathematics': [
        { name: 'Relations and Functions', description: 'Types of relations and functions.' },
        { name: 'Inverse Trigonometric Functions', description: 'Inverse trigonometric functions and their properties.' },
        { name: 'Matrices', description: 'Types of matrices and matrix operations.' },
        { name: 'Determinants', description: 'Properties of determinants and their applications.' },
        { name: 'Continuity and Differentiability', description: 'Continuity, differentiability, and derivatives.' },
        { name: 'Application of Derivatives', description: 'Applications of derivatives in various fields.' },
        { name: 'Integrals', description: 'Indefinite and definite integrals.' },
        { name: 'Applications of Integrals', description: 'Applications of integrals in finding areas.' },
        { name: 'Differential Equations', description: 'Formation and solution of differential equations.' },
        { name: 'Vector Algebra', description: 'Vector operations and properties.' },
        { name: 'Three-Dimensional Geometry', description: 'Lines and planes in 3D space.' },
        { name: 'Linear Programming', description: 'Optimization problems using linear programming.' },
        { name: 'Probability', description: 'Conditional probability, Bayes\' theorem, and probability distributions.' },
      ],
      'Economics': [
        { name: 'Introduction to Macroeconomics', description: 'Introductory Macroeconomics' },
        { name: 'National Income Accounting', description: 'Introductory Macroeconomics' },
        { name: 'Money and Banking', description: 'Introductory Macroeconomics' },
        { name: 'Determination of Income and Employment', description: 'Introductory Macroeconomics' },
        { name: 'Government Budget and the Economy', description: 'Introductory Macroeconomics' },
        { name: 'Open Economy Macroeconomics', description: 'Introductory Macroeconomics' },
        { name: 'Indian Economy on the Eve of Independence', description: 'Indian Economic Development' },
        { name: 'Indian Economy 1950-1990', description: 'Indian Economic Development' },
        { name: 'Liberalisation, Privatisation and Globalisation: An Appraisal', description: 'Indian Economic Development' },
        { name: 'Poverty', description: 'Indian Economic Development' },
        { name: 'Human Capital Formation in India', description: 'Indian Economic Development' },
        { name: 'Rural Development', description: 'Indian Economic Development' },
        { name: 'Employment: Growth, Informalisation and Other Issues', description: 'Indian Economic Development' },
        { name: 'Infrastructure', description: 'Indian Economic Development' },
        { name: 'Environment and Sustainable Development', description: 'Indian Economic Development' },
        { name: 'Comparative Development Experiences of India and Its Neighbours', description: 'Indian Economic Development' }
      ],
      'Business Studies': [
        { name: 'Nature and Significance of Management', description: 'Introduction to management.' },
        { name: 'Principles of Management', description: 'Principles of scientific management and Fayol\'s principles.' },
        { name: 'Business Environment', description: 'Dimensions of business environment.' },
        { name: 'Planning', description: 'Steps in planning process.' },
        { name: 'Organising', description: 'Steps in organizing process.' },
        { name: 'Staffing', description: 'Steps in staffing process.' },
        { name: 'Directing', description: 'Elements of directing.' },
        { name: 'Controlling', description: 'Steps in controlling process.' },
        { name: 'Financial Management', description: 'Objectives and functions of financial management.' },
        { name: 'Financial Markets', description: 'Money market and capital market.' },
        { name: 'Marketing', description: 'Marketing mix and marketing management.' },
        { name: 'Consumer Protection', description: 'Consumer rights and responsibilities.' },
      ],
      'Accountancy': [],
      'History': [
        { name: 'From the Beginning of Time', description: 'Human evolution and early societies.' },
        { name: 'Writing and City Life', description: 'Development of writing and urban civilizations.' },
        { name: 'An Empire Across Three Continents', description: 'Roman Empire.' },
        { name: 'The Central Islamic Lands', description: 'Rise and spread of Islam.' },
        { name: 'Nomadic Empires', description: 'Mongol Empire.' },
        { name: 'The Three Orders', description: 'Feudal society in medieval Europe.' },
        { name: 'Changing Cultural Traditions', description: 'Renaissance and Reformation.' },
        { name: 'Confrontation of Cultures', description: 'Encounters between different cultures.' },
        { name: 'The Industrial Revolution', description: 'Industrialization and its impact.' },
        { name: 'Displacing Indigenous Peoples', description: 'Colonization and its effects on indigenous populations.' },
        { name: 'Paths to Modernisation', description: 'Modernization in East Asia.' },
      ],
      'Geography': [
        { name: 'Geography as a Discipline', description: 'Nature and scope of geography.' },
        { name: 'The Origin and Evolution of the Earth', description: 'Theories of Earth\'s origin.' },
        { name: 'Interior of the Earth', description: 'Structure and composition of Earth\'s interior.' },
        { name: 'Distribution of Oceans and Continents', description: 'Continental drift and plate tectonics.' },
        { name: 'Minerals and Rocks', description: 'Types and characteristics of minerals and rocks.' },
        { name: 'Geomorphic Processes', description: 'Endogenic and exogenic forces shaping Earth\'s surface.' },
        { name: 'Landforms and their Evolution', description: 'Formation and evolution of landforms.' },
        { name: 'Composition and Structure of Atmosphere', description: 'Layers of atmosphere and atmospheric composition.' },
        { name: 'Solar Radiation, Heat Balance and Temperature', description: 'Insolation, heat budget, and temperature distribution.' },
        { name: 'Atmospheric Circulation and Weather Systems', description: 'Pressure systems and wind patterns.' },
        { name: 'Water in the Atmosphere', description: 'Humidity, condensation, and precipitation.' },
        { name: 'World Climate and Climate Change', description: 'Major climate types and climate change.' },
        { name: 'Water (Oceans)', description: 'Ocean relief, temperature, and salinity.' },
        { name: 'Movements of Ocean Water', description: 'Ocean currents, tides, and waves.' },
        { name: 'Life on the Earth', description: 'Biosphere and ecosystems.' },
        { name: 'Biodiversity and Conservation', description: 'Importance of biodiversity and its conservation.' },
        { name: 'Introduction to Maps', description: 'Basic concepts of maps.' },
        { name: 'Map Scale', description: 'Understanding map scales.' },
        { name: 'Latitude, Longitude and Time', description: 'Locating places using latitude and longitude.' },
        { name: 'Map Projections', description: 'Types of map projections.' },
        { name: 'Topographical Maps', description: 'Interpretation of topographical maps.' },
        { name: 'Introduction to Aerial Photographs', description: 'Understanding aerial photographs.' },
        { name: 'Introduction to Remote Sensing', description: 'Principles and applications of remote sensing.' },
        { name: 'Weather Instruments, Maps and Charts', description: 'Use of weather instruments and maps.' },
      ],
      'Political Science': [
        { name: 'The Cold War Era', description: 'The Cold War and its impact on international politics.' },
        { name: 'The End of Bipolarity', description: 'End of Cold War and rise of new world order.' },
        { name: 'US Hegemony in World Politics', description: 'US dominance in the post-Cold War era.' },
        { name: 'Alternative Centers of Power', description: 'Rise of new power centers (e.g., EU, ASEAN, China).' },
        { name: 'Contemporary South Asia', description: 'Political developments in South Asia.' },
        { name: 'International Organizations', description: 'Role and functions of international organizations (e.g., UN).' },
        { name: 'Security in the Contemporary World', description: 'Traditional and non-traditional notions of security.' },
        { name: 'Environment and Natural Resources', description: 'Environmental concerns and resource management.' },
        { name: 'Globalisation', description: 'Economic, political, and cultural aspects of globalization.' },
        { name: 'Challenges of Nation-Building', description: 'Challenges faced by India after independence.' },
        { name: 'Era of One-Party Dominance', description: 'Congress dominance in Indian politics.' },
        { name: 'Politics of Planned Development', description: 'Planning and economic development in India.' },
        { name: 'India\'s External Relations', description: 'India\'s foreign policy.' },
        { name: 'Challenges to and Restoration of the Congress System', description: 'Challenges to Congress dominance and its restoration.' },
        { name: 'The Crisis of Democratic Order', description: 'Emergency and its impact on Indian democracy.' },
        { name: 'Regional Aspirations', description: 'Regional movements and autonomy demands.' },
        { name: 'Recent Developments in Indian Politics', description: 'Recent political developments in India.' },
      ],
      'Psychology': [
        { name: 'Variations in Psychological Attributes', description: 'Individual differences in psychological attributes.' },
        { name: 'Self and Personality', description: 'Concepts of self and theories of personality.' },
        { name: 'Meeting Life Challenges', description: 'Stress, coping, and well-being.' },
        { name: 'Psychological Disorders', description: 'Classification and causes of psychological disorders.' },
        { name: 'Therapeutic Approaches', description: 'Different approaches to psychotherapy.' },
        { name: 'Attitude and Social Cognition', description: 'Formation and change of attitudes.' },
        { name: 'Social Influence and Group Processes', description: 'Social influence and group dynamics.' },
      ],
      'Sociology': [
        { name: 'Introducing Indian Society', description: 'Introduction to Indian society.' },
        { name: 'The Demographic Structure of Indian Society', description: 'Population characteristics of India.' },
        { name: 'Social Institutions: Continuity and Change', description: 'Family, marriage, education, and religion.' },
        { name: 'Patterns of Social Inequality and Exclusion', description: 'Caste, class, and gender inequalities.' },
        { name: 'The Challenges of Cultural Diversity', description: 'Cultural diversity and its challenges.' },
        { name: 'Structural Change', description: 'Industrialization, urbanization, and social change.' },
        { name: 'Cultural Change', description: 'Modernization, Westernization, and Sanskritization.' },
        { name: 'Change and Development in Rural Society', description: 'Rural development and social change.' },
        { name: 'Change and Development in Industrial Society', description: 'Industrialization and its impact on society.' },
        { name: 'Social Movements', description: 'Types and theories of social movements.' },
      ],
    }
  };

  const chaptersToDisplay = (ncertChapters[grade || ''] && ncertChapters[grade || ''][subject || '']) || [];

  return (
    <div className="chapter-list-container">
      <h1 className="text-center">Class {grade} - {subject} Chapters</h1>
      <div className="row">
        {chaptersToDisplay.length > 0 ? (
          chaptersToDisplay.map((chapter, index) => (
            <div key={index} className="col-md-4 mb-4">
              <div className="card chapter-card">
                <div className="card-body">
                  <h5 className="card-title">{chapter.name}</h5>
                  <p className="card-text">{chapter.description}</p>
                  <Link to={`/resources/cbse/class/${grade}/${subject}/chapters/${chapter.name}`} className="btn btn-primary">View Chapter</Link>
                </div>
              </div>
            </div>
          ))
        ) : (
          <div className="col-12 text-center">
            <p>No chapters found for this subject and class yet.</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default ChapterList;
